# Generated migration for Token model and Restaurant updates

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets
from django.utils import timezone
from datetime import timedelta


def atribuir_restaurantes_ao_superusuario(apps, schema_editor):
    Usuario = apps.get_model(settings.AUTH_USER_MODEL)
    Restaurante = apps.get_model('puceats', 'Restaurant')
    
    superusuario = Usuario.objects.filter(is_superuser=True).first()
    
    if not superusuario:
        print("Nenhum superusuário encontrado. Crie um com: python manage.py createsuperuser")
        return
    
    restaurantes = Restaurante.objects.filter(owner__isnull=True)
    quantidade = restaurantes.update(owner=superusuario)
    if quantidade > 0:
        print(f"✓ {quantidade} restaurante(s) atribuído(s) ao superusuário '{superusuario.username}'")
# Generated by Django 5.2.8 on 2025-11-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Criar model Category
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone da sua UI (opcional)', max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        # Criar model Restaurant
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurantes/logos/')),
                ('description', models.TextField(blank=True, help_text='Descrição curta do restaurante')),
                ('cuisine_type', models.CharField(choices=[('brasileira', 'Brasileira'), ('japonesa', 'Japonesa'), ('italiana', 'Italiana'), ('árabe', 'Árabe'), ('vegana', 'Vegana'), ('cafeteria', 'Cafeteria'), ('lanches', 'Lanches'), ('internacional', 'Internacional'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('establishment_type', models.CharField(choices=[('restaurante', 'Restaurante'), ('lanchonete', 'Lanchonete'), ('barraca', 'Barraca')], default='restaurante', max_length=20, verbose_name='Tipo de Estabelecimento')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('building', models.CharField(blank=True, help_text='Ex: Frings, Pilotis, etc.', max_length=80)),
                ('opening_hours', models.CharField(blank=True, help_text='Ex: Seg–Sex 8h–22h', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('price_level', models.PositiveSmallIntegerField(default=1, help_text='1–5 (quanto mais alto, mais caro)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        # Criar model Token
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Já foi usado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_used', to=settings.AUTH_USER_MODEL, verbose_name='Usado por')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-created_at'],
            },
        ),
        
        # Criar model Dish
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pratos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='puceats.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='puceats.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        # Atribuir restaurantes ao superusuário
        migrations.RunPython(atribuir_restaurantes_ao_superusuario),
    ]
