# Generated by Django 5.2.7 on 2025-11-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puceats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["name"],
                "verbose_name": "Prato",
                "verbose_name_plural": "Pratos",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={
                "ordering": ["name"],
                "verbose_name": "Restaurante",
                "verbose_name_plural": "Restaurantes",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Nome do ícone da sua UI (opcional)",
                max_length=80,
                verbose_name="Ícone",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=60, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Disponível"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="puceats.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pratos/", verbose_name="Imagem"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="is_gluten_free",
            field=models.BooleanField(default=False, verbose_name="Sem Glúten"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="is_vegan",
            field=models.BooleanField(default=False, verbose_name="Vegano"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="is_vegetarian",
            field=models.BooleanField(default=False, verbose_name="Vegetariano"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="puceats.restaurant",
                verbose_name="Restaurante",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="building",
            field=models.CharField(
                blank=True,
                help_text="Ex: Frings, Pilotis, etc.",
                max_length=80,
                verbose_name="Prédio",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="cuisine_type",
            field=models.CharField(
                choices=[
                    ("brasileira", "Brasileira"),
                    ("japonesa", "Japonesa"),
                    ("italiana", "Italiana"),
                    ("árabe", "Árabe"),
                    ("vegana", "Vegana"),
                    ("cafeteria", "Cafeteria"),
                    ("lanches", "Lanches"),
                    ("internacional", "Internacional"),
                    ("outros", "Outros"),
                ],
                default="outros",
                max_length=30,
                verbose_name="Tipo de Cozinha",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descrição curta do restaurante",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="instagram",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="restaurantes/logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hours",
            field=models.CharField(
                blank=True,
                help_text="Ex: Seg–Sex 8h–22h",
                max_length=120,
                verbose_name="Horário de Funcionamento",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="price_level",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="1–5 (quanto mais alto, mais caro)",
                verbose_name="Nível de Preço",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="website",
            field=models.URLField(blank=True, verbose_name="Site"),
        ),
    ]
