# Generated by Django 5.2.7 on 2025-12-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puceats", "0002_adicionar_owner_e_establishment_type"),
        ("puceats", "0002_alter_category_options_alter_dish_options_and_more"),
    ]

    operations = []
