# Generated by Django 5.2.7 on 2025-12-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puceats", "0003_merge_20251208_2038"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nome do Marcador"),
                ),
                (
                    "marker_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurante"),
                            ("point_of_interest", "Ponto de Interesse"),
                            ("other", "Outro"),
                        ],
                        default="restaurant",
                        max_length=30,
                        verbose_name="Tipo de Marcador",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Ex: -22.9794", verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Ex: -43.2329", verbose_name="Longitude"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "icon_color",
                    models.CharField(
                        default="#9CCC65",
                        help_text="Código hexadecimal (ex: #9CCC65)",
                        max_length=7,
                        verbose_name="Cor do Ícone",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marker",
                        to="puceats.restaurant",
                        verbose_name="Restaurante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marcador",
                "verbose_name_plural": "Marcadores",
                "ordering": ["name"],
            },
        ),
    ]
